import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Register',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru, en">
			<body
				className={inter.className}
				style={{
					background: 'linear-gradient(180deg, rgba(152,90,206,1), #bf8aed)',
					width: '100%',
					height: '100vh',
					overflow: 'hidden',
				}}
			>
				{children}
			</body>
		</html>
	);
}
